spring:
  application:
    name: service-commande

server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commande_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Kawtar

service:
  client:
    url: http://localhost:8082
  produit:
    url: http://localhost:8083