# Configuration SPÉCIFIQUE service-produit
server:
  port: 8083

spring:
  application:
    name: service-produit
  # Base de données service-produit
  datasource:
    url: jdbc:mysql://localhost:3306/produit_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: Kawtar
  
  # RabbitMQ spécifique
  rabbitmq:
    listener:
      simple:
        auto-startup: true
        concurrency: 1
        max-concurrency: 3
    deserialization:
      trust-all: true

# URLs des autres services
service:
  client:
    url: http://localhost:8082

# Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
    instances:
      clientService:
        baseConfig: default
  
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      clientService:
        baseConfig: default

logging:
  level:
    com.exemple.produit: DEBUG
    com.exemple.produit.service.CommandeEventHandler: DEBUG