# Configuration SPÉCIFIQUE service-commande
spring:
  application:
    name: service-commande

server:
  port: 8084

# Base de données service-commande
datasource:
  url: jdbc:mysql://localhost:3306/commande_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  username: root
  password: Kawtar
  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

# URLs des autres services
service:
  client:
    url: http://localhost:8082
  produit:
    url: http://localhost:8083